#!/usr/bin/python

import sys
import re

input = sys.stdin.read()

mobj = re.findall('([0-9]{1,2}):([0-9]{2})-([0-9]{1,2}):([0-9]{2})', input)
if not mobj:
	sys.exit(0)

sum = 0
for m in mobj:
	partial = int(m[3]) + 60 * int(m[2]) - int(m[1]) - 60 * int(m[0])
	sum += partial

print "{0}:{1:02}".format(sum/60, sum%60)
